"""empty message

Revision ID: 3057fb762b15
Revises: 63f2c88b1fdf
Create Date: 2018-06-06 15:57:29.588883

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3057fb762b15'
down_revision = '63f2c88b1fdf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('short', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'short')
    # ### end Alembic commands ###
