"""update post field - title

Revision ID: 63f2c88b1fdf
Revises: 88c7837fece5
Create Date: 2018-05-28 20:36:43.442844

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63f2c88b1fdf'
down_revision = '88c7837fece5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_post_title'), 'post', ['title'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_post_title'), table_name='post')
    # ### end Alembic commands ###
